#cloud-config
package_update: true
packages:
  - qemu-kvm
  - libvirt
  - virt-install
  - qemu-img
  - libguestfs-tools-c
  - python3

runcmd:
  - [bash, -lc, "cat >/usr/local/sbin/oci-vnic2-routing.sh <<'EOF'\n#!/usr/bin/env bash\nset -euo pipefail\n\nSECONDARY_IF=\"${secondary_vnic_interface}\"\nTABLE_ID=200\nTABLE_NAME=vnic2\n\nif ! ip link show \"$${SECONDARY_IF}\" >/dev/null 2>&1; then\n  echo \"Secondary interface $${SECONDARY_IF} not present; skipping policy routing setup.\"\n  exit 0\nfi\n\nip link set \"$${SECONDARY_IF}\" up || true\nSECONDARY_CIDR=\"$(ip -o -4 addr show dev \"$${SECONDARY_IF}\" | awk '{print $4}' | head -n1)\"\nif [[ -z \"$${SECONDARY_CIDR}\" ]]; then\n  echo \"Secondary interface $${SECONDARY_IF} has no IPv4 address yet; skipping policy routing setup.\"\n  exit 0\nfi\n\nSECONDARY_IP=\"$${SECONDARY_CIDR%/*}\"\nSUBNET_CIDR=\"$(ip -4 route show dev \"$${SECONDARY_IF}\" proto kernel scope link | awk 'NR==1 {print $1}')\"\n\nif [[ -z \"$${SUBNET_CIDR}\" ]]; then\n  SUBNET_CIDR=\"$${SECONDARY_CIDR}\"\nfi\n\nSECONDARY_GW=\"$(ip route | awk -v dev=\"$${SECONDARY_IF}\" '$1 == \"default\" && $0 ~ (\"dev \" dev) {print $3; exit}')\"\nif [[ -z \"$${SECONDARY_GW}\" ]]; then\n  export SECONDARY_CIDR\n  SECONDARY_GW=\"$(python3 - <<'PY'\nimport ipaddress, os\ncidr = os.environ.get('SECONDARY_CIDR')\nnet = ipaddress.ip_interface(cidr).network\nprint(str(next(net.hosts())))\nPY\n)\"\nfi\n\ngrep -q "^$${TABLE_ID} $${TABLE_NAME}$" /etc/iproute2/rt_tables || echo "$${TABLE_ID} $${TABLE_NAME}" >> /etc/iproute2/rt_tables\n\nip route replace "$${SUBNET_CIDR}" dev "$${SECONDARY_IF}" src "$${SECONDARY_IP}" table "$${TABLE_NAME}"\nip route replace default via "$${SECONDARY_GW}" dev "$${SECONDARY_IF}" table "$${TABLE_NAME}"\nip rule add from "$${SECONDARY_IP}/32" table "$${TABLE_NAME}" priority 1000 2>/dev/null || true\nip rule add to "$${SECONDARY_IP}/32" table "$${TABLE_NAME}" priority 1001 2>/dev/null || true\n\ncat >/etc/sysctl.d/99-kove-multi-vnic.conf <<SYSCTL\nnet.ipv4.conf.all.rp_filter=2\nnet.ipv4.conf.default.rp_filter=2\nnet.ipv4.conf.eth0.rp_filter=2\nnet.ipv4.conf.${secondary_vnic_interface}.rp_filter=2\nSYSCTL\nsysctl --system >/dev/null 2>&1 || true\n\necho \"Configured source-based routing for $${SECONDARY_IF} ($${SECONDARY_IP}) via table $${TABLE_NAME}.\"\nEOF\nchmod 0755 /usr/local/sbin/oci-vnic2-routing.sh"]
  - [bash, -lc, "set -euxo pipefail; mkdir -p /opt/kove"]
  - [bash, -lc, "set -euxo pipefail; if systemctl list-unit-files | grep -q '^libvirtd.service'; then systemctl enable --now libvirtd; else systemctl enable --now virtqemud.socket virtnetworkd.socket virtstoraged.socket; fi"]
  - [bash, -lc, "set -euxo pipefail; CANDIDATES='192.168.122.0/24 192.168.123.0/24 172.16.122.0/24'; SELECTED=''; for cidr in $${CANDIDATES}; do if ! ip -4 route | awk '{print $1}' | grep -q "^$${cidr}$"; then SELECTED=$${cidr}; break; fi; done; [ -n "$${SELECTED}" ] || SELECTED='192.168.122.0/24'; GW=$(python3 - <<'PY'\nimport ipaddress, os\nnet = ipaddress.ip_network(os.environ['SELECTED'], strict=False)\nprint(str(next(net.hosts())))\nPY\n); NETMASK=$(python3 - <<'PY'\nimport ipaddress, os\nnet = ipaddress.ip_network(os.environ['SELECTED'], strict=False)\nprint(str(net.netmask))\nPY\n); cat >/tmp/default-net.xml <<EOF\n<network>\n  <name>default</name>\n  <forward mode='nat'/>\n  <bridge name='virbr0' stp='on' delay='0'/>\n  <ip address='$${GW}' netmask='$${NETMASK}'>\n    <dhcp>\n      <range start='$${GW%.*}.2' end='$${GW%.*}.254'/>\n    </dhcp>\n  </ip>\n</network>\nEOF\nvirsh --connect qemu:///system net-destroy default 2>/dev/null || true\nvirsh --connect qemu:///system net-undefine default 2>/dev/null || true\nvirsh --connect qemu:///system net-define /tmp/default-net.xml\nvirsh --connect qemu:///system net-start default\nvirsh --connect qemu:///system net-autostart default || true"]
  - [bash, -lc, "cat >${setup_script_path} <<'EOF'\n#!/usr/bin/env bash\nset -euo pipefail\n\nVM_NAME=\"$${1:-}\"\nDISK_PATH=\"$${2:-}\"\nVCPUS=\"$${3:-}\"\nMEMORY_MB=\"$${4:-}\"\n\n[[ -z \"$${VM_NAME}\" ]] && VM_NAME=\"${guest_vm_name}\"\n[[ -z \"$${DISK_PATH}\" ]] && DISK_PATH=\"${guest_disk_path}\"\n[[ -z \"$${VCPUS}\" ]] && VCPUS=\"${guest_vcpus}\"\n[[ -z \"$${MEMORY_MB}\" ]] && MEMORY_MB=\"${guest_memory_mb}\"\n\nif [[ ! -f \"$${DISK_PATH}\" ]]; then\n  echo \"ERROR: Disk image not found: $${DISK_PATH}\"\n  echo \"Copy/convert the appliance disk to this host first, then rerun.\"\n  exit 1\nfi\n\nvirsh --connect qemu:///system destroy \"$${VM_NAME}\" 2>/dev/null || true\nvirsh --connect qemu:///system undefine \"$${VM_NAME}\" --nvram 2>/dev/null || virsh --connect qemu:///system undefine \"$${VM_NAME}\" 2>/dev/null || true\nvirsh --connect qemu:///system net-start default 2>/dev/null || true\nvirsh --connect qemu:///system net-autostart default || true\n\nvirt-install \\\n  --connect qemu:///system \\\n  --name \"$${VM_NAME}\" \\\n  --memory \"$${MEMORY_MB}\" \\\n  --vcpus \"$${VCPUS}\" \\\n  --cpu Westmere,-svm,-x2apic,-tsc-deadline,-invtsc \\\n  --machine pc \\\n  --disk path=\"$${DISK_PATH}\",format=qcow2,bus=sata,target=sda \\\n  --network network=default,model=e1000 \\\n  --os-variant rhel8.7 \\\n  --graphics vnc,listen=127.0.0.1 \\\n  --serial pty \\\n  --console pty,target_type=serial \\\n  --import \\\n  --noautoconsole\n\nvirsh --connect qemu:///system autostart \"$${VM_NAME}\" || true\nvirsh --connect qemu:///system domifaddr \"$${VM_NAME}\" || true\nvirsh --connect qemu:///system vncdisplay \"$${VM_NAME}\" || true\n\necho \"MC guest deploy complete for $${VM_NAME}.\"\nEOF\nchmod 750 ${setup_script_path}"]
  - [bash, -lc, "echo 'MC host bootstrap complete. Run: sudo ${setup_script_path} ${guest_vm_name} ${guest_disk_path} ${guest_vcpus} ${guest_memory_mb}' >/etc/motd.d/99-kove-mc"]
  - [bash, -lc, "if ip link show ${secondary_vnic_interface} >/dev/null 2>&1; then /usr/local/sbin/oci-vnic2-routing.sh || true; fi"]
  - [bash, -lc, "if command -v nmcli >/dev/null 2>&1; then nmcli con mod ${secondary_vnic_interface} connection.autoconnect yes || true; fi"]
